"""
PDF 导出：标准剧本排版
- font: Courier 12pt (English) + SimSun fallback (Chinese)
- margins: Left 1.5" Right 1.0" Top 1.0" Bottom 1.0"
- A4 paper, 12pt leading
"""

import sys as _sys
from pathlib import Path
from fpdf import FPDF

# ── Font paths (Windows system) ──────────────────────────────

def _resolve_font(name: str) -> Path:
    """Resolve a font file under the Windows Fonts directory."""
    if _sys.platform == "win32":
        fonts_dir = Path("C:/Windows/Fonts")
    else:
        for candidate in ("/usr/share/fonts", "/usr/local/share/fonts"):
            p = Path(candidate)
            if p.exists():
                fonts_dir = p
                break
        else:
            fonts_dir = Path("/c/Windows/Fonts")  # Git Bash / WSL interop

    return fonts_dir / name


SIMSUN_TTC = _resolve_font("simsun.ttc")

# ── Layout constants (inches → user units at 72 DPI) ────────
DPI = 72
MARGIN_LEFT = 1.5 * DPI
MARGIN_RIGHT = 1.0 * DPI
MARGIN_TOP = 1.0 * DPI
MARGIN_BOTTOM = 1.0 * DPI

# Character cue: centered at ~3.7" from left edge
CHAR_CUE_X = 3.7 * DPI
# Dialogue block: left 2.5" from left, right 2.5" from right
DIALOGUE_LEFT = 2.5 * DPI
DIALOGUE_RIGHT_MARGIN = 2.5 * DPI
# Parenthetical: left 3.1" from left
PAREN_LEFT = 3.1 * DPI

PAGE_W = 210  # A4 width in mm (portrait)
PAGE_H = 297  # A4 height in mm

FONT_SIZE = 12
LEADING = 18  # line height in pt (increased for CJK readability, was 14)


class ScreenplayPDF(FPDF):
    """PDF writer in standard screenplay format (Courier 12pt)."""

    def __init__(self, title: str = ""):
        super().__init__(orientation="P", unit="mm", format="A4")
        self._script_title = title
        self._y = 0.0            # current y in mm
        self.set_auto_page_break(True, MARGIN_BOTTOM * 25.4 / 72)

        if SIMSUN_TTC.exists():
            self.add_font("SimSun", "", str(SIMSUN_TTC), uni=True)

        self._font_name = "SimSun" if SIMSUN_TTC.exists() else "Courier"

    # ── helpers ──────────────────────────────────────────────

    def _mm(self, pt: float) -> float:
        """Convert points to mm."""
        return pt * 25.4 / 72

    def _x_from_left(self, pt: float) -> float:
        """Convert pt-from-left to mm offset including left margin."""
        return self._mm(pt)

    def _new_page_if_needed(self, needed_mm: float = 15):
        """Break page if remaining space < needed_mm."""
        if self.get_y() > self.h - self.b_margin - needed_mm:
            self.add_page()

    # ── public API ───────────────────────────────────────────

    def title_page(self):
        """Render a simple title page (optional, called before content)."""
        self.add_page()
        self.ln(80)
        self.set_font(self._font_name, "", 24)
        self.multi_cell(0, 12, self._script_title, align="C")
        self.ln(10)
        self.set_font(self._font_name, "", 12)
        self.cell(0, 10, "Generated by AI Script Tool", align="C")

    def action(self, text: str):
        """Render an action / stage-direction line."""
        self._new_page_if_needed(LEADING * 2)
        self.set_font(self._font_name, "", FONT_SIZE)
        x = self._x_from_left(MARGIN_LEFT)
        w = self.w - x - self._mm(MARGIN_RIGHT)
        self.set_x(x)
        self.multi_cell(w, self._mm(LEADING), text.strip(), align="L")

    def character_cue(self, name: str):
        """Render a character name above dialogue."""
        self._new_page_if_needed(LEADING * 2)
        self.set_font(self._font_name, "", FONT_SIZE)
        x = self._x_from_left(CHAR_CUE_X)
        self.set_x(x)
        # BUGFIX: new_y="NEXT" ensures dialogue starts on the next line below the character name
        self.cell(self._mm(40), self._mm(LEADING), name.strip().upper(),
                  new_x="LMARGIN", new_y="NEXT")

    def dialogue(self, text: str):
        """Render dialogue text (indented block)."""
        self.set_font(self._font_name, "", FONT_SIZE)
        x = self._x_from_left(DIALOGUE_LEFT)
        w = self.w - self._mm(DIALOGUE_LEFT) - self._mm(DIALOGUE_RIGHT_MARGIN)
        self.set_x(x)
        self.multi_cell(w, self._mm(LEADING), text.strip(), align="L")

    def parenthetical(self, text: str):
        """Render a parenthetical / direction inside dialogue."""
        self.set_font(self._font_name, "", FONT_SIZE)
        x = self._x_from_left(PAREN_LEFT)
        w = self.w - self._mm(PAREN_LEFT) - self._mm(DIALOGUE_RIGHT_MARGIN)
        self.set_x(x)
        self.multi_cell(w, self._mm(LEADING), f"({text.strip()})", align="L")

    def scene_heading(self, text: str):
        """Render a scene heading (slug line) in bold."""
        self._new_page_if_needed(LEADING * 2)
        self.set_font(self._font_name, "", FONT_SIZE)
        x = self._x_from_left(MARGIN_LEFT)
        w = self.w - x - self._mm(MARGIN_RIGHT)
        self.set_x(x)
        self.multi_cell(w, self._mm(LEADING), text.strip().upper(), align="L")

    def transition(self, text: str):
        """Render a transition (e.g. CUT TO:)."""
        self._new_page_if_needed(LEADING * 2)
        self.set_font(self._font_name, "", FONT_SIZE)
        x = self._x_from_left(MARGIN_LEFT)
        w = self.w - x - self._mm(MARGIN_RIGHT)
        self.set_x(x)
        self.multi_cell(w, self._mm(LEADING), text.strip(), align="R")

    def note(self, text: str):
        """Render an author note (grey / smaller, optional)."""
        self._new_page_if_needed(LEADING * 2)
        self.set_font(self._font_name, "", 9)
        x = self._x_from_left(MARGIN_LEFT)
        w = self.w - x - self._mm(MARGIN_RIGHT)
        self.set_x(x)
        self.multi_cell(w, self._mm(10), f"[NOTE] {text.strip()}", align="L")

    def blank_line(self):
        """Add vertical space (one leading)."""
        self.ln(self._mm(LEADING))


def generate_screenplay_pdf(yaml_data: dict, title: str = "Screenplay") -> bytes:
    """
    Convert structured YAML data (per script-yaml-schema) into a PDF
    with standard screenplay formatting.

    Returns PDF bytes.
    """
    pdf = ScreenplayPDF(title=title)
    pdf.set_margin(MARGIN_TOP * 25.4 / 72)
    pdf.add_page()

    # ── Title header ────────────────────────────────────────
    # Left-aligned: use set_x to position at left margin, then cell with explicit width
    pdf.set_font(pdf._font_name, "", 16)
    x_title = pdf._x_from_left(MARGIN_LEFT)
    pdf.set_x(x_title)
    w_title = pdf.w - x_title - pdf._mm(MARGIN_RIGHT)
    pdf.cell(w_title, 10, title, align="L", new_x="LMARGIN", new_y="NEXT")
    pdf.ln(5)

    # ── Meta info ───────────────────────────────────────────
    meta = yaml_data.get("meta", {})
    if meta:
        pdf.set_font(pdf._font_name, "", 9)
        info_parts = []
        if meta.get("source_novel"):
            info_parts.append(f"原著: {meta['source_novel']}")
        if meta.get("source_author"):
            info_parts.append(f"作者: {meta['source_author']}")
        if meta.get("script_type"):
            info_parts.append(f"类型: {meta['script_type']}")
        if meta.get("version"):
            info_parts.append(f"版本: {meta['version']}")
        info_line = " | ".join(info_parts)
        x_meta = pdf._x_from_left(MARGIN_LEFT)
        pdf.set_x(x_meta)
        w_meta = pdf.w - x_meta - pdf._mm(MARGIN_RIGHT)
        pdf.cell(w_meta, 6, info_line, align="L", new_x="LMARGIN", new_y="NEXT")
        pdf.ln(3)

    # Divider
    pdf.set_line_width(0.4)
    y = pdf.get_y()
    pdf.line(pdf.l_margin, y, pdf.w - pdf.r_margin, y)
    pdf.ln(5)

    # ── Characters ──────────────────────────────────────────
    characters = yaml_data.get("characters", [])
    if characters:
        pdf.set_font(pdf._font_name, "", 11)
        pdf.cell(0, 7, "人物表", align="L", new_x="LMARGIN", new_y="NEXT")
        pdf.ln(2)
        for ch in characters:
            cid = ch.get("id", "")
            name = ch.get("name", cid)
            desc = ch.get("description", "")
            role = ch.get("role", "")
            pdf.set_font(pdf._font_name, "", 10)
            if role:
                pdf.cell(0, 6, f"  {name}  ({role})  {desc}", align="L", new_x="LMARGIN", new_y="NEXT")
            else:
                pdf.cell(0, 6, f"  {name}  {desc}", align="L", new_x="LMARGIN", new_y="NEXT")
        pdf.ln(5)
        # Divider
        y = pdf.get_y()
        pdf.line(pdf.l_margin, y, pdf.w - pdf.r_margin, y)
        pdf.ln(5)

    # ── Scenes ──────────────────────────────────────────────
    scenes = yaml_data.get("scenes", [])
    char_lookup = {c.get("id", ""): c.get("name", c.get("id", "")) for c in characters}

    for i, scene in enumerate(scenes):
        sid = scene.get("id", f"scene_{i+1:03d}")
        setting = scene.get("setting", {})
        location = setting.get("location", "")
        time_of_day = setting.get("time", "")

        # Scene heading
        heading_parts = [f"SCENE {i+1}"]
        if location:
            heading_parts.append(location.upper())
        if time_of_day:
            heading_parts.append(time_of_day.upper())
        pdf.scene_heading("  —  ".join(heading_parts))
        pdf.blank_line()

        # Optional setting description
        setting_desc = setting.get("description", "")
        if setting_desc:
            pdf.action(setting_desc)

        # Characters present
        present = scene.get("characters_present", [])
        if present:
            names = [char_lookup.get(cid, cid) for cid in present]
            pdf.action(f"出场: {'，'.join(names)}")
            pdf.blank_line()

        # Content blocks
        content = scene.get("content", [])
        for block in content:
            btype = block.get("type", "action")
            btext = block.get("text", "")

            if btype == "action":
                pdf.action(btext)
            elif btype == "dialogue":
                character_id = block.get("character", "")
                char_name = char_lookup.get(character_id, character_id)
                direction = block.get("direction", "")
                pdf.character_cue(char_name)
                if direction:
                    pdf.parenthetical(direction)
                pdf.dialogue(btext)
            elif btype == "transition":
                pdf.transition(btext)
            elif btype == "note":
                pdf.note(btext)
            else:
                pdf.action(btext)

        # Space between scenes
        pdf.blank_line()
        pdf.blank_line()

    # ── Fin ─────────────────────────────────────────────────
    pdf.blank_line()
    pdf.set_font(pdf._font_name, "", 12)
    x_end = pdf._x_from_left(MARGIN_LEFT)
    pdf.set_x(x_end)
    w_end = pdf.w - x_end - pdf._mm(MARGIN_RIGHT)
    pdf.cell(w_end, 10, "— END —", align="L", new_x="LMARGIN", new_y="NEXT")

    return pdf.output()
